# Get current global drought conditions
name: droughtData

# When
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 10 * * *'

jobs:
  getData:
    # Runs on
    runs-on: macos-latest

    # Load repo, install R
    steps:
    - uses: actions/checkout@main
    - uses: r-lib/actions/setup-r@v2

    # Install libraries
    - name: Install packages
      run: |
        R -e 'install.packages("here")'
        R -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/ncdf4/ncdf4_1.19.tar.gz", repos=NULL, type="mac.binary")'
        R -e 'install.packages("OpenImageR")'
   
   # Run R script
    - name: Get data
      run: Rscript R/ncdfV4toV3.R

    # Add data, commit, push
    - name: Commit
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data pull: ${timestamp}" || exit 0
        git push
